spring:
  application:
    name: telemetry-processor
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/telemetrypulse}
    username: ${SPRING_DATASOURCE_USERNAME:telemetrypulse}
    password: ${SPRING_DATASOURCE_PASSWORD:telemetrypulse}
  flyway:
    enabled: true
  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
